/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppIntegracoesRouteImport } from './routes/_app.integracoes'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCentrosRouteImport } from './routes/_app.centros'
import { Route as AppAprovacoesRouteImport } from './routes/_app.aprovacoes'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCentrosRoute = AppCentrosRouteImport.update({
  id: '/centros',
  path: '/centros',
  getParentRoute: () => AppRoute,
} as any)
const AppAprovacoesRoute = AppAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/aprovacoes': typeof AppAprovacoesRoute
  '/centros': typeof AppCentrosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/aprovacoes': typeof AppAprovacoesRoute
  '/centros': typeof AppCentrosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/integracoes': typeof AppIntegracoesRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/aprovacoes': typeof AppAprovacoesRoute
  '/_app/centros': typeof AppCentrosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/integracoes': typeof AppIntegracoesRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprovacoes'
    | '/centros'
    | '/configuracoes'
    | '/integracoes'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aprovacoes'
    | '/centros'
    | '/configuracoes'
    | '/integracoes'
    | '/relatorios'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/aprovacoes'
    | '/_app/centros'
    | '/_app/configuracoes'
    | '/_app/integracoes'
    | '/_app/relatorios'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integracoes': {
      id: '/_app/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/centros': {
      id: '/_app/centros'
      path: '/centros'
      fullPath: '/centros'
      preLoaderRoute: typeof AppCentrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aprovacoes': {
      id: '/_app/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AppAprovacoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAprovacoesRoute: typeof AppAprovacoesRoute
  AppCentrosRoute: typeof AppCentrosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprovacoesRoute: AppAprovacoesRoute,
  AppCentrosRoute: AppCentrosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
